In [1]:
import pandas as pd
import numpy as np
from langdetect import detect

In [2]:
data=pd.read_csv('coursera_data.csv')

In [3]:
data.head()

Course_Name Company_Offering  \
0                  Google Data Analytics           Google   
1                   Google Cybersecurity           Google   
2             Google Project Management:           Google   
3                       IBM Data Science              IBM   
4  Google Digital Marketing & E-commerce           Google   

                                       Skills_Gained  Ratings  \
0  Data Analysis, Spreadsheets, SQL (Programming ...      4.8   
1  Cybersecurity, Incident Response, Network Secu...      4.8   
2  Project Management, Operations Management, Str...      4.8   
3  Python (Programming Language), Data Science, S...      4.6   
4  Digital Marketing, Marketing, Marketing Manage...      4.8   

   Number_of_Ratings                                        Course_Link  
0             142000  https://www.coursera.org/professional-certific...  
1              27000  https://www.coursera.org/professional-certific...  
2             105000  https://www.coursera.org/professional-certific...  
3             124000  https://www.coursera.org/professional-certific...  
4              25000  https://www.coursera.org/professional-certific...

In [4]:
print(data.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Course_Name        1000 non-null   object 
 1   Company_Offering   1000 non-null   object 
 2   Skills_Gained      887 non-null    object 
 3   Ratings            994 non-null    float64
 4   Number_of_Ratings  1000 non-null   int64  
 5   Course_Link        1000 non-null   object 
dtypes: float64(1), int64(1), object(4)
memory usage: 47.0+ KB
None


In [5]:
print(data.describe())

          Ratings  Number_of_Ratings
count  994.000000        1000.000000
mean     4.670322        8571.915000
std      0.198165       20198.277126
min      2.700000           0.000000
25%      4.600000         488.500000
50%      4.700000        3000.000000
75%      4.800000        8000.000000
max      5.000000      270000.000000


In [6]:
print("Missing values:")
print(data.isnull().sum())

Missing values:
Course_Name            0
Company_Offering       0
Skills_Gained        113
Ratings                6
Number_of_Ratings      0
Course_Link            0
dtype: int64


In [7]:
data['Ratings'].fillna(data['Ratings'].median(), inplace=True)


data['Skills_Gained'].fillna('Unknown', inplace=True)

In [8]:
print("Missing values:")
print(data.isnull().sum())

Missing values:
Course_Name          0
Company_Offering     0
Skills_Gained        0
Ratings              0
Number_of_Ratings    0
Course_Link          0
dtype: int64


In [9]:
data['Number_of_Ratings'].fillna(0, inplace=True)

In [10]:
print("Missing values:")
print(data.isnull().sum())

Missing values:
Course_Name          0
Company_Offering     0
Skills_Gained        0
Ratings              0
Number_of_Ratings    0
Course_Link          0
dtype: int64


In [11]:
def detect_language(text):
    try:
        language = detect(text)
        return language
    except:
        return 'unknown'

In [12]:
data.head(5)

Course_Name Company_Offering  \
0                  Google Data Analytics           Google   
1                   Google Cybersecurity           Google   
2             Google Project Management:           Google   
3                       IBM Data Science              IBM   
4  Google Digital Marketing & E-commerce           Google   

                                       Skills_Gained  Ratings  \
0  Data Analysis, Spreadsheets, SQL (Programming ...      4.8   
1  Cybersecurity, Incident Response, Network Secu...      4.8   
2  Project Management, Operations Management, Str...      4.8   
3  Python (Programming Language), Data Science, S...      4.6   
4  Digital Marketing, Marketing, Marketing Manage...      4.8   

   Number_of_Ratings                                        Course_Link  
0             142000  https://www.coursera.org/professional-certific...  
1              27000  https://www.coursera.org/professional-certific...  
2             105000  https://www.coursera.org/professional-certific...  
3             124000  https://www.coursera.org/professional-certific...  
4              25000  https://www.coursera.org/professional-certific...

In [13]:
data['tags']=data['Course_Name']+','+data['Skills_Gained']

In [14]:
new_df=data[['Course_Name','tags']]
new_df['tags'][0]

'Google Data Analytics,Data Analysis, Spreadsheets, SQL (Programming Language), Data Visualization, R (Programming Language), Data Cleansing, Business Communication, Business Communications, Data Integrity, Tableau (Business Intelligence Software), Data Quality, Advanced Analytics, Analysis, Analytics, Business Analysis, Data Collection, Data Management, Graphing, Information Privacy, Relational Databases, Statistical Graphics, Statistics, Teamwork, Text Mining, Unstructured Data'

In [15]:
new_df.loc[:, 'tags'] = new_df['tags'].str.replace(',', ' ')
new_df.loc[:, 'tags'] = new_df['tags'].str.replace('  ', ' ')

/tmp/ipykernel_26985/3714198266.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.loc[:, 'tags'] = new_df['tags'].str.replace(',', ' ')
/tmp/ipykernel_26985/3714198266.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.loc[:, 'tags'] = new_df['tags'].str.replace('  ', ' ')


In [16]:
new_df['tags'][0]

'Google Data Analytics Data Analysis Spreadsheets SQL (Programming Language) Data Visualization R (Programming Language) Data Cleansing Business Communication Business Communications Data Integrity Tableau (Business Intelligence Software) Data Quality Advanced Analytics Analysis Analytics Business Analysis Data Collection Data Management Graphing Information Privacy Relational Databases Statistical Graphics Statistics Teamwork Text Mining Unstructured Data'

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv = CountVectorizer(max_features=15000,stop_words='english')

In [40]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [41]:
print(vectors)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [42]:
import nltk

In [43]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [44]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [45]:
new_df['tags'] = new_df['tags'].apply(stem) #applying stemming on the tags column

/tmp/ipykernel_26985/3741851974.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem) #applying stemming on the tags column


In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
similarity = cosine_similarity(vectors)

In [49]:
similarity

array([[1.        , 0.15770888, 0.17865525, ..., 0.02838665, 0.2908008 ,
        0.25286087],
       [0.15770888, 1.        , 0.30630941, ..., 0.13384167, 0.03337392,
        0.05610479],
       [0.17865525, 0.30630941, 1.        , ..., 0.01567531, 0.01661196,
        0.20944737],
       ...,
       [0.02838665, 0.13384167, 0.01567531, ..., 1.        , 0.59520387,
        0.02440477],
       [0.2908008 , 0.03337392, 0.01661196, ..., 0.59520387, 1.        ,
        0.02586303],
       [0.25286087, 0.05610479, 0.20944737, ..., 0.02440477, 0.02586303,
        1.        ]])

In [53]:
def recommend(course, rating_weight=0.5):
    course_index = new_df[new_df['Course_Name'] == course].index[0]

    distances = similarity[course_index]

    ratings = data['Ratings']

    ratings_numeric = pd.to_numeric(ratings, errors='coerce')

    ratings_numeric.fillna(0, inplace=True)
    
    normalized_ratings = (ratings_numeric - ratings_numeric.min()) / (ratings_numeric.max() - ratings_numeric.min())
    rating_similarity = cosine_similarity([normalized_ratings])[0]

    combined_similarity = (1 - rating_weight) * distances + rating_weight * rating_similarity
    course_list = sorted(list(enumerate(combined_similarity)), reverse=True, key=lambda x: x[1])[1:15]

    print("Recommended Courses:")
    for i in course_list:
        recommended_course_name = new_df.iloc[i[0]]['Course_Name']
        print(recommended_course_name)



recommend('Google Data Analytics')


Recommended Courses:
Business Data Management and Communication
IBM Data Analyst
Foundations: Data, Data, Everywhere
Prepare Data for Exploration
Applied Data Science with R
IBM Business Intelligence (BI) Analyst
Data Literacy: Exploring and Visualizing Data
Excel Skills for Business
Data Analysis and Visualization Foundations
Introduction to Data Analytics
SAS Visual Business Analytics
Excel Skills for Data Analytics and Visualization
Google Data Analytics Capstone: Complete a Case Study
Process Data from Dirty to Clean
